/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.flp.gccw;

import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.flp.gccw.model.ListConnectionModel;
import org.flp.gccw.model.ListTablesModel;
import org.flp.gccw.model.RelationListBoxModel;
import org.flp.gccw.model.Table;
import org.flp.gccw.model.TableThemeModel;
import org.flp.gccw.sql.DatabaseTableLister;
import org.netbeans.api.db.explorer.ConnectionManager;
import org.netbeans.api.db.explorer.DatabaseConnection;

public final class GCCVisualPanel1 extends JPanel {
    private Connection connection;
    /**
     * Creates new form GCCVisualPanel1
     */
    public GCCVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Alap beállítások";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tableTextJTextField = new javax.swing.JTextField();
        dbConnectionJComboBox = new javax.swing.JComboBox();
        tablesJComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tableThemeJComboBox = new javax.swing.JComboBox();
        connectionJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        relationschipJList = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 300));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GCCVisualPanel1.class, "GCCVisualPanel1.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(GCCVisualPanel1.class, "GCCVisualPanel1.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(GCCVisualPanel1.class, "GCCVisualPanel1.jLabel3.text")); // NOI18N

        tableTextJTextField.setText(org.openide.util.NbBundle.getMessage(GCCVisualPanel1.class, "GCCVisualPanel1.tableTextJTextField.text")); // NOI18N

        dbConnectionJComboBox.setModel(new ListConnectionModel());
        dbConnectionJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbConnectionJComboBoxActionPerformed(evt);
            }
        });

        tablesJComboBox.setModel(new ListTablesModel());
        tablesJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablesJComboBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(GCCVisualPanel1.class, "GCCVisualPanel1.jLabel4.text")); // NOI18N

        tableThemeJComboBox.setModel(new TableThemeModel());

        org.openide.awt.Mnemonics.setLocalizedText(connectionJButton, org.openide.util.NbBundle.getMessage(GCCVisualPanel1.class, "GCCVisualPanel1.connectionJButton.text")); // NOI18N
        connectionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionJButtonActionPerformed(evt);
            }
        });

        relationschipJList.setModel(new RelationListBoxModel());
        jScrollPane1.setViewportView(relationschipJList);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(GCCVisualPanel1.class, "GCCVisualPanel1.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dbConnectionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tableThemeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tablesJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tableTextJTextField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectionJButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dbConnectionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectionJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tablesJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tableThemeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableTextJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dbConnectionJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbConnectionJComboBoxActionPerformed
        // TODO add your handling code here:
        if(this.dbConnectionJComboBox.getSelectedIndex() == 0){
            ConnectionManager.getDefault().showAddConnectionDialog(null);
            ((ListConnectionModel)this.dbConnectionJComboBox.getModel()).refresh();
        }
    }//GEN-LAST:event_dbConnectionJComboBoxActionPerformed

    private void connectionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionJButtonActionPerformed
        // TODO add your handling code here:
        DatabaseConnection dc = ((ListConnectionModel)this.dbConnectionJComboBox.getModel()).getDbConnection(this.dbConnectionJComboBox.getSelectedIndex());
        if(dc != null){
            this.connection = dc.getJDBCConnection();
            //a DatabaseMetaData osztály segítségével kilistázzuk a táblákat.
            ((ListTablesModel)this.tablesJComboBox.getModel()).refresh(connection);
        }
    }//GEN-LAST:event_connectionJButtonActionPerformed

    private void tablesJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablesJComboBoxActionPerformed
        // TODO add your handling code here:
        DatabaseTableLister dT = new DatabaseTableLister(connection);
        ((RelationListBoxModel)this.relationschipJList.getModel()).removeAll();
        ((RelationListBoxModel)this.relationschipJList.getModel()).addAll(dT.detectRelationSchip((String)this.tablesJComboBox.getSelectedItem()));
    }//GEN-LAST:event_tablesJComboBoxActionPerformed

    public String getTable(){
        return (String)tablesJComboBox.getSelectedItem();
    }
    
    public String getTheme(){
        return (String)tableThemeJComboBox.getSelectedItem();
    }
    
    public String getTableText(){
        return tableTextJTextField.getText();
    }

    public Connection getConnection() {
        return connection;
    }
    
    public ArrayList<Table> getRelationShipTables(){
        return (ArrayList)this.relationschipJList.getSelectedValuesList();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectionJButton;
    private javax.swing.JComboBox dbConnectionJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList relationschipJList;
    private javax.swing.JTextField tableTextJTextField;
    private javax.swing.JComboBox tableThemeJComboBox;
    private javax.swing.JComboBox tablesJComboBox;
    // End of variables declaration//GEN-END:variables
}
