/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.flp.gccw;

import javax.swing.JCheckBox;
import javax.swing.JPanel;

public final class GCCVisualPanel5 extends JPanel {

    /**
     * Creates new form GCCVisualPanel5
     */
    public GCCVisualPanel5() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Step #5";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unsetPrintJCombo = new javax.swing.JCheckBox();
        unsetAddJCombo = new javax.swing.JCheckBox();
        unsetEditJCombo = new javax.swing.JCheckBox();
        unsetDeleteJCombo = new javax.swing.JCheckBox();
        unsetListJCombo = new javax.swing.JCheckBox();
        unsetReadJCombo = new javax.swing.JCheckBox();
        unsetBackToListJCombo = new javax.swing.JCheckBox();
        unsetBootstrapJCombo = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        unsetExportJCombo = new javax.swing.JCheckBox();
        unsetJqueryJCombo = new javax.swing.JCheckBox();
        unsetJqueryUIJCombo = new javax.swing.JCheckBox();
        unsetOperationsJCombo = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 300));

        org.openide.awt.Mnemonics.setLocalizedText(unsetPrintJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetPrintJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(unsetAddJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetAddJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(unsetEditJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetEditJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(unsetDeleteJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetDeleteJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(unsetListJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetListJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(unsetReadJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetReadJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(unsetBackToListJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetBackToListJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(unsetBootstrapJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetBootstrapJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(unsetExportJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetExportJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(unsetJqueryJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetJqueryJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(unsetJqueryUIJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetJqueryUIJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(unsetOperationsJCombo, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.unsetOperationsJCombo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel6.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel9.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel10.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel11.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel12.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel13, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel13.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel14, org.openide.util.NbBundle.getMessage(GCCVisualPanel5.class, "GCCVisualPanel5.jLabel14.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(unsetDeleteJCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsetEditJCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsetExportJCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsetJqueryJCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsetJqueryUIJCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsetListJCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsetReadJCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsetPrintJCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsetOperationsJCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsetBootstrapJCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsetBackToListJCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsetAddJCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetAddJCombo)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetBackToListJCombo)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetBootstrapJCombo)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetDeleteJCombo)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetEditJCombo)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetExportJCombo)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetJqueryJCombo)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetJqueryUIJCombo)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetListJCombo)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetOperationsJCombo)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetPrintJCombo)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsetReadJCombo)
                    .addComponent(jLabel11))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * Setters Getters
     * 
     */
    
    public boolean getUnsetAddJCombo() {
        return unsetAddJCombo.isSelected();
    }

    public boolean getUnsetBackToListJCombo() {
        return unsetBackToListJCombo.isSelected();
    }
    
    public boolean getUnsetBootstrapJCombo(){
        return unsetBootstrapJCombo.isSelected();
    }
    
    public boolean getUnsetDeleteJCombo() {
        return unsetDeleteJCombo.isSelected();
    }

    public boolean getUnsetEditJCombo() {
        return unsetEditJCombo.isSelected();
    }
    
    public boolean getUnsetExportJCombo() {
        return unsetExportJCombo.isSelected();
    }

    public boolean getUnsetJquery() {
        return unsetJqueryJCombo.isSelected();
    }

    public boolean getUnsetJqueryUI() {
        return unsetJqueryUIJCombo.isSelected();
    }
    
    public boolean getUnsetListJCombo() {
        return unsetListJCombo.isSelected();
    }

    public boolean getUnsetOperationsJCombo() {
        return unsetOperationsJCombo.isSelected();
    }

    public boolean getUnsetReadJCombo() {
        return unsetReadJCombo.isSelected();
    }

    public boolean getUnsetPrintJCombo() {
        return unsetPrintJCombo.isSelected();
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox unsetAddJCombo;
    private javax.swing.JCheckBox unsetBackToListJCombo;
    private javax.swing.JCheckBox unsetBootstrapJCombo;
    private javax.swing.JCheckBox unsetDeleteJCombo;
    private javax.swing.JCheckBox unsetEditJCombo;
    private javax.swing.JCheckBox unsetExportJCombo;
    private javax.swing.JCheckBox unsetJqueryJCombo;
    private javax.swing.JCheckBox unsetJqueryUIJCombo;
    private javax.swing.JCheckBox unsetListJCombo;
    private javax.swing.JCheckBox unsetOperationsJCombo;
    private javax.swing.JCheckBox unsetPrintJCombo;
    private javax.swing.JCheckBox unsetReadJCombo;
    // End of variables declaration//GEN-END:variables

    
}
